### ISSUE TITLE
mutable strings' is_empty member is not needed.

### ISSUE THREAD

**Issue by manvscode** [manchicken/libmanchicken#9]
Instead of storing a variable if a string is empty, test if the string is empty.

For example, change:
<pre>
short mutable_string_is_empty(mutable_string_t *var) {
	return (var->is_empty == 'Y');
}
</pre>

To this:

<pre>
short mutable_string_is_empty(mutable_string_t *var) {
        /* maybe the first part isn't needed if data is never NULL */
	return var->data && *var->data == '\0';
}
</pre>

Also, you should probably rewrite this to support C99.  C99 is now supported in Visual Studio so the library would be portable to Mac OS X, Linux and Windows.  Otherwise, keep it as it is (i.e C89)

If you do use C99, you can include stdbool.h and use the bool type.

**Comment by manchicken** [comment]
This issue is now closed.
